[bans]
multiple-versions = "allow"
deny = ["aws-lc", "aws-lc-rs", "aws-lc-sys", "native-tls", "openssl"]

[licenses]
allow = [
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "MIT",
    "Zlib",
    "Unicode-3.0",
    "Unlicense",                      # https://unlicense.org/
]


[advisories]
ignore = []
